# Generated by Django 5.2.3 on 2025-06-18 17:33

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chain_id', models.PositiveIntegerField(unique=True)),
                ('native_token_symbol', models.CharField(max_length=20)),
                ('rpc_url', models.URLField()),
                ('explorer_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BridgeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_pair', models.CharField(max_length=100)),
                ('total_volume', models.DecimalField(decimal_places=18, max_digits=30)),
                ('total_transactions', models.PositiveIntegerField()),
                ('avg_completion_time', models.PositiveIntegerField(help_text='Average completion time in minutes')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BridgeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('contract_address', models.CharField(blank=True, max_length=42, null=True)),
                ('decimals', models.PositiveSmallIntegerField(default=18)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BridgeQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('fee_amount', models.DecimalField(decimal_places=18, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_time', models.PositiveIntegerField(help_text='Estimated time in minutes')),
                ('valid_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes_from', to='bridge.bridgenetwork')),
                ('to_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes_to', to='bridge.bridgenetwork')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.bridgetoken')),
            ],
        ),
        migrations.CreateModel(
            name='BridgeTokenNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=42)),
                ('min_bridge_amount', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=30)),
                ('is_active', models.BooleanField(default=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.bridgenetwork')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.bridgetoken')),
            ],
            options={
                'unique_together': {('token', 'network')},
            },
        ),
        migrations.AddField(
            model_name='bridgetoken',
            name='networks',
            field=models.ManyToManyField(through='bridge.BridgeTokenNetwork', to='bridge.bridgenetwork'),
        ),
        migrations.CreateModel(
            name='BridgeFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_fee', models.DecimalField(decimal_places=18, max_digits=30)),
                ('max_fee', models.DecimalField(decimal_places=18, max_digits=30)),
                ('from_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_from', to='bridge.bridgenetwork')),
                ('to_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_to', to='bridge.bridgenetwork')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.bridgetoken')),
            ],
            options={
                'unique_together': {('from_network', 'to_network', 'token')},
            },
        ),
        migrations.CreateModel(
            name='BridgeTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_token', models.CharField(max_length=64)),
                ('from_address', models.CharField(max_length=42)),
                ('to_address', models.CharField(max_length=42)),
                ('deposit_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('receive_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bridge.bridgequote')),
            ],
            options={
                'indexes': [models.Index(fields=['user_token'], name='bridge_brid_user_to_d78725_idx'), models.Index(fields=['status'], name='bridge_brid_status_27295c_idx'), models.Index(fields=['deposit_tx_hash'], name='bridge_brid_deposit_f4c7f9_idx'), models.Index(fields=['receive_tx_hash'], name='bridge_brid_receive_3a4bb1_idx')],
            },
        ),
    ]
