# Generated by Django 5.2.1 on 2025-06-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0002_bridgefee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridgenetwork',
            name='is_evm',
            field=models.BooleanField(default=True),
        ),
    ]
