# Generated by Django 5.2.3 on 2025-06-14 15:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(help_text='ETH address', max_length=42, unique=True)),
                ('user_token', models.CharField(help_text='HMAC-SHA256(user_identity)', max_length=64)),
                ('balance_commitment', models.CharField(help_text='SHA3-256(balance+salt)', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['address'], name='idx_escrow_address'), models.Index(fields=['user_token'], name='idx_escrow_user')],
            },
        ),
        migrations.CreateModel(
            name='SystemWallet',
            fields=[
                ('address', models.CharField(help_text='ETH address', max_length=42, primary_key=True, serialize=False)),
                ('private_key_enc', models.TextField(help_text='Age-encrypted private key')),
                ('current_balance', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('collected_fees', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('last_swept_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['current_balance'], name='idx_wallet_balance')],
            },
        ),
    ]
