# Generated by Django 5.2.3 on 2025-06-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowwallet',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Amount in USDT', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='escrowwallet',
            name='buyer_address',
            field=models.CharField(blank=True, help_text='ETH address of the buyer', max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='escrowwallet',
            name='seller_address',
            field=models.CharField(blank=True, help_text='ETH address of the seller', max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='escrowwallet',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('funded', 'Funded'), ('released', 'Released'), ('disputed', 'Disputed')], default='created', help_text='Current status of the escrow', max_length=10),
        ),
        migrations.AddIndex(
            model_name='escrowwallet',
            index=models.Index(fields=['status'], name='idx_escrow_status'),
        ),
    ]
