# Generated by Django 5.2.3 on 2025-06-14 15:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escrow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='P2PListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seller_token', models.CharField(help_text='HMAC-SHA256(seller_identity)', max_length=64)),
                ('crypto_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('crypto_currency', models.CharField(default='USDT', max_length=10)),
                ('crypto_amount', models.DecimalField(decimal_places=6, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('fiat_currency', models.CharField(default='USD', max_length=10)),
                ('usdt_amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.SmallIntegerField(choices=[(1, 'Cash'), (2, 'Hawala'), (3, 'Other')], help_text='1=Cash,2=Hawala,3=Other')),
                ('description', models.TextField(blank=True, null=True)),
                ('instructions_enc', models.TextField(blank=True, help_text='Encrypted with session key', null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Funded'), (3, 'Reserved'), (4, 'Completed'), (5, 'Expired')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('escrow_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escrow.escrowwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='P2PTrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_token', models.CharField(max_length=64)),
                ('seller_token', models.CharField(max_length=64)),
                ('escrow_tx_hash', models.CharField(max_length=66)),
                ('usdt_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('payment_proof_hash', models.CharField(blank=True, help_text='SHA3-256(payment_details)', max_length=64, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Created'), (1, 'Funded'), (2, 'PaymentSent'), (3, 'Completed'), (4, 'Disputed'), (5, 'Canceled')], default=0, help_text='0=Created,1=Funded,2=PaymentSent,3=Completed,4=Disputed,5=Canceled')),
                ('fee_amount', models.DecimalField(decimal_places=6, default=0.0025, help_text='0.25% platform fee', max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trades', to='p2p.p2plisting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='p2plisting',
            index=models.Index(fields=['seller_token'], name='idx_listing_seller'),
        ),
        migrations.AddIndex(
            model_name='p2plisting',
            index=models.Index(fields=['status'], name='idx_listing_status'),
        ),
        migrations.AddIndex(
            model_name='p2plisting',
            index=models.Index(fields=['payment_method'], name='idx_listing_payment_type'),
        ),
        migrations.AddIndex(
            model_name='p2plisting',
            index=models.Index(fields=['expires_at'], name='idx_listing_expiry'),
        ),
        migrations.AddIndex(
            model_name='p2ptrade',
            index=models.Index(fields=['listing'], name='idx_trade_listing'),
        ),
        migrations.AddIndex(
            model_name='p2ptrade',
            index=models.Index(fields=['buyer_token'], name='idx_trade_buyer'),
        ),
        migrations.AddIndex(
            model_name='p2ptrade',
            index=models.Index(fields=['seller_token'], name='idx_trade_seller'),
        ),
        migrations.AddIndex(
            model_name='p2ptrade',
            index=models.Index(fields=['status'], name='idx_trade_status'),
        ),
    ]
