# Generated by Django 5.2.3 on 2025-06-14 15:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('p2p', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeDispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('initiator_token', models.CharField(max_length=64)),
                ('evidence_hashes', models.TextField(blank=True, help_text='Array of SHA3-256(evidence_files)', null=True)),
                ('evidence_ipfs_cid', models.CharField(blank=True, help_text='IPFS CID for encrypted evidence bundle', max_length=64, null=True)),
                ('resolution', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'BuyerFavored'), (2, 'SellerFavored'), (3, 'SplitFunds')], default=0, help_text='0=Pending,1=BuyerFavored,2=SellerFavored,3=SplitFunds')),
                ('admin_sig', models.CharField(blank=True, help_text='Ed25519 signature of resolution', max_length=96, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='p2p.p2ptrade')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trade'], name='idx_dispute_trade')],
            },
        ),
    ]
